# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class BeaconConceptType(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, id: str=None, idmap: str=None, frequency: int=None):  # noqa: E501
        """BeaconConceptType - a model defined in Swagger

        :param id: The id of this BeaconConceptType.  # noqa: E501
        :type id: str
        :param idmap: The idmap of this BeaconConceptType.  # noqa: E501
        :type idmap: str
        :param frequency: The frequency of this BeaconConceptType.  # noqa: E501
        :type frequency: int
        """
        self.swagger_types = {
            'id': str,
            'idmap': str,
            'frequency': int
        }

        self.attribute_map = {
            'id': 'id',
            'idmap': 'idmap',
            'frequency': 'frequency'
        }

        self._id = id
        self._idmap = idmap
        self._frequency = frequency

    @classmethod
    def from_dict(cls, dikt) -> 'BeaconConceptType':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The BeaconConceptType of this BeaconConceptType.  # noqa: E501
        :rtype: BeaconConceptType
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> str:
        """Gets the id of this BeaconConceptType.

        the type    # noqa: E501

        :return: The id of this BeaconConceptType.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this BeaconConceptType.

        the type    # noqa: E501

        :param id: The id of this BeaconConceptType.
        :type id: str
        """

        self._id = id

    @property
    def idmap(self) -> str:
        """Gets the idmap of this BeaconConceptType.

        The URL to execute the exactmatches API call on the id  # noqa: E501

        :return: The idmap of this BeaconConceptType.
        :rtype: str
        """
        return self._idmap

    @idmap.setter
    def idmap(self, idmap: str):
        """Sets the idmap of this BeaconConceptType.

        The URL to execute the exactmatches API call on the id  # noqa: E501

        :param idmap: The idmap of this BeaconConceptType.
        :type idmap: str
        """

        self._idmap = idmap

    @property
    def frequency(self) -> int:
        """Gets the frequency of this BeaconConceptType.

        the number of instances of the specified type   # noqa: E501

        :return: The frequency of this BeaconConceptType.
        :rtype: int
        """
        return self._frequency

    @frequency.setter
    def frequency(self, frequency: int):
        """Sets the frequency of this BeaconConceptType.

        the number of instances of the specified type   # noqa: E501

        :param frequency: The frequency of this BeaconConceptType.
        :type frequency: int
        """

        self._frequency = frequency
