# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class BeaconStatementSubject(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, id: str=None, name: str=None, type: str=None):  # noqa: E501
        """BeaconStatementSubject - a model defined in Swagger

        :param id: The id of this BeaconStatementSubject.  # noqa: E501
        :type id: str
        :param name: The name of this BeaconStatementSubject.  # noqa: E501
        :type name: str
        :param type: The type of this BeaconStatementSubject.  # noqa: E501
        :type type: str
        """
        self.swagger_types = {
            'id': str,
            'name': str,
            'type': str
        }

        self.attribute_map = {
            'id': 'id',
            'name': 'name',
            'type': 'type'
        }

        self._id = id
        self._name = name
        self._type = type

    @classmethod
    def from_dict(cls, dikt) -> 'BeaconStatementSubject':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The BeaconStatementSubject of this BeaconStatementSubject.  # noqa: E501
        :rtype: BeaconStatementSubject
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> str:
        """Gets the id of this BeaconStatementSubject.

        CURIE-encoded identifier of concept   # noqa: E501

        :return: The id of this BeaconStatementSubject.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this BeaconStatementSubject.

        CURIE-encoded identifier of concept   # noqa: E501

        :param id: The id of this BeaconStatementSubject.
        :type id: str
        """

        self._id = id

    @property
    def name(self) -> str:
        """Gets the name of this BeaconStatementSubject.

        human readable label of subject concept  # noqa: E501

        :return: The name of this BeaconStatementSubject.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this BeaconStatementSubject.

        human readable label of subject concept  # noqa: E501

        :param name: The name of this BeaconStatementSubject.
        :type name: str
        """

        self._name = name

    @property
    def type(self) -> str:
        """Gets the type of this BeaconStatementSubject.

        a semantic group for the subject concept (specified as a code gene, pathway, disease, etc. - see [Biolink Model](https://biolink.github.io/biolink-model) for the full list of codes)   # noqa: E501

        :return: The type of this BeaconStatementSubject.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type: str):
        """Sets the type of this BeaconStatementSubject.

        a semantic group for the subject concept (specified as a code gene, pathway, disease, etc. - see [Biolink Model](https://biolink.github.io/biolink-model) for the full list of codes)   # noqa: E501

        :param type: The type of this BeaconStatementSubject.
        :type type: str
        """

        self._type = type
