# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class BeaconAnnotation(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, id: str=None, label: str=None, type: str=None, date: str=None):  # noqa: E501
        """BeaconAnnotation - a model defined in Swagger

        :param id: The id of this BeaconAnnotation.  # noqa: E501
        :type id: str
        :param label: The label of this BeaconAnnotation.  # noqa: E501
        :type label: str
        :param type: The type of this BeaconAnnotation.  # noqa: E501
        :type type: str
        :param date: The date of this BeaconAnnotation.  # noqa: E501
        :type date: str
        """
        self.swagger_types = {
            'id': str,
            'label': str,
            'type': str,
            'date': str
        }

        self.attribute_map = {
            'id': 'id',
            'label': 'label',
            'type': 'type',
            'date': 'date'
        }

        self._id = id
        self._label = label
        self._type = type
        self._date = date

    @classmethod
    def from_dict(cls, dikt) -> 'BeaconAnnotation':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The BeaconAnnotation of this BeaconAnnotation.  # noqa: E501
        :rtype: BeaconAnnotation
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> str:
        """Gets the id of this BeaconAnnotation.

        CURIE-encoded identifier to an associated external resources (e.g. PMID of a pubmed citation)   # noqa: E501

        :return: The id of this BeaconAnnotation.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this BeaconAnnotation.

        CURIE-encoded identifier to an associated external resources (e.g. PMID of a pubmed citation)   # noqa: E501

        :param id: The id of this BeaconAnnotation.
        :type id: str
        """

        self._id = id

    @property
    def label(self) -> str:
        """Gets the label of this BeaconAnnotation.

        canonical human readable and searchable label of the annotation (i.e. comment, matched sentence, etc.)   # noqa: E501

        :return: The label of this BeaconAnnotation.
        :rtype: str
        """
        return self._label

    @label.setter
    def label(self, label: str):
        """Sets the label of this BeaconAnnotation.

        canonical human readable and searchable label of the annotation (i.e. comment, matched sentence, etc.)   # noqa: E501

        :param label: The label of this BeaconAnnotation.
        :type label: str
        """

        self._label = label

    @property
    def type(self) -> str:
        """Gets the type of this BeaconAnnotation.

        Gene Ontology Evidence Code (http://www.geneontology.org/page/guide-go-evidence-codes)   # noqa: E501

        :return: The type of this BeaconAnnotation.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type: str):
        """Sets the type of this BeaconAnnotation.

        Gene Ontology Evidence Code (http://www.geneontology.org/page/guide-go-evidence-codes)   # noqa: E501

        :param type: The type of this BeaconAnnotation.
        :type type: str
        """

        self._type = type

    @property
    def date(self) -> str:
        """Gets the date of this BeaconAnnotation.

        publication date of annotation (generally of format 'yyyy-mm-dd')   # noqa: E501

        :return: The date of this BeaconAnnotation.
        :rtype: str
        """
        return self._date

    @date.setter
    def date(self, date: str):
        """Sets the date of this BeaconAnnotation.

        publication date of annotation (generally of format 'yyyy-mm-dd')   # noqa: E501

        :param date: The date of this BeaconAnnotation.
        :type date: str
        """

        self._date = date
